name: RITBuddy CD

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: rashmitha6/ritbuddy
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push existing image
      run: |
        docker tag existing-image-name:tag docker.io/yourusername/ritbuddy:tag
        docker push docker.io/yourusername/ritbuddy:tag